name: CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.runner }}
    strategy:
      matrix:
        config:
          #- { runner: windows-latest, platform: win-x86,   ext: dll }
          - { runner: windows-latest, platform: win-x64,   ext: dll }
          #- { runner: windows-latest, platform: win-arm64, ext: dll }
          - { runner: ubuntu-latest,  platform: linux-x64, ext: so }
          #- { runner: macos-latest,   platform: osx-x64,   ext: dylib }
          #- { runner: macos-latest,   platform: osx-arm64, ext: dylib }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'

      - name: Build
        run: dotnet publish osu.Native -c Release -r ${{ matrix.config.platform }} -o artifacts

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.platform }}
          path: artifacts/osu.Native.${{ matrix.config.ext }}
